# Generated by Django 3.1.3 on 2020-11-18 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sunglare', '0003_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='owner',
        ),
    ]
